var model = {
    "A_CNC001": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 1, mac_no: 'A001' },
    "A_CNC002": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 2, mac_no: 'A002' },
    "A_CNC003": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 3, mac_no: 'A003' },
    "A_CNC004": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 4, mac_no: 'A004' },
    "A_CNC005": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 5, mac_no: 'A005' },
    "A_CNC006": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 6, mac_no: 'A006' },
    "A_CNC007": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 7, mac_no: 'A007' },
    "A_CNC008": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 8, mac_no: 'A008' },
    "A_CNC009": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 9, mac_no: 'A009' },
    "A_CNC010": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 10, mac_no: 'A010' },
    "A_CNC011": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 11, mac_no: 'A011' },
    "A_CNC012": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 12, mac_no: 'A012' },
    "A_CNC013": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 13, mac_no: 'A013' },
    "A_CNC014": { enable: true, display: true, model_id: 'jiagongzhongxin', mac_id: 14, mac_no: 'A014' },
    "A_CNC015": { enable: true, display: false, model_id: 'avg', mac_id: 15, mac_no: 'A015' },
    "A_CNC016": { enable: true, display: true, model_id: 'mazak', mac_id: 16, mac_no: 'A016' },
    "A_CNC017": { enable: true, display: true, model_id: 'mazak', mac_id: 17, mac_no: 'A017' },
    "A_CNC018": { enable: true, display: true, model_id: 'mazak', mac_id: 18, mac_no: 'A018' },
    "A_CNC019": { enable: true, display: true, model_id: 'mazak', mac_id: 19, mac_no: 'A019' },
    "A_CNC020": { enable: false, display: false, model_id: 'avg', mac_id: -1, mac_no: '' },
    "A_CNC021": { enable: false, display: false, model_id: 'avg', mac_id: -2, mac_no: '' },
    "A_CNC022": { enable: false, display: false, model_id: 'avg', mac_id: -3, mac_no: '' },
    "A_CNC023": { enable: false, display: false, model_id: 'avg', mac_id: -4, mac_no: '' },
    "A_CNC024": { enable: true, display: false, model_id: 'guanjiejiqiren', mac_id: 20, mac_no: 'A020' },
    "A_CNC025": { enable: true, display: false, model_id: 'guanjiejiqiren', mac_id: 21, mac_no: 'A021' },
    "A_CNC026": { enable: true, display: false, model_id: 'qinxiji', mac_id: 22, mac_no: 'A022' },
    "A_CNC027": { enable: true, display: false, model_id: 'cangku', mac_id: 23, mac_no: 'A023' },
    "A_CNC028": { enable: false, display: false, model_id: 'daogui', mac_id: 24, mac_no: '' },

    "B_CNC001": { enable: true, display: false, model_id: 'workbache', mac_id: 25, mac_no: 'B001' },
    "B_CNC002": { enable: true, display: false, model_id: 'workbache', mac_id: 26, mac_no: 'B002' },
    "B_CNC003": { enable: true, display: false, model_id: 'workbache', mac_id: 27, mac_no: 'B003' },
    "B_CNC004": { enable: true, display: false, model_id: 'workbache', mac_id: 28, mac_no: 'B004' },
    "B_CNC005": { enable: true, display: false, model_id: 'workbache', mac_id: 29, mac_no: 'B005' },
    "B_CNC006": { enable: true, display: false, model_id: 'workbache', mac_id: 30, mac_no: 'B006' },
    "B_CNC007": { enable: true, display: false, model_id: 'workbache', mac_id: 31, mac_no: 'B007' },
    "B_CNC008": { enable: true, display: false, model_id: 'workbache', mac_id: 32, mac_no: 'B008' },
    "B_CNC009": { enable: true, display: false, model_id: 'workbache', mac_id: 33, mac_no: 'B009' },
    "B_CNC010": { enable: true, display: false, model_id: 'workbache', mac_id: 34, mac_no: 'B010' },
    "B_CNC011": { enable: true, display: false, model_id: 'workbache', mac_id: 35, mac_no: 'B011' },
    "B_CNC012": { enable: true, display: false, model_id: 'workbache', mac_id: 36, mac_no: 'B012' },
    "B_CNC013": { enable: true, display: false, model_id: 'workbache', mac_id: 37, mac_no: 'B013' },
    "B_CNC014": { enable: true, display: false, model_id: 'workbache', mac_id: 38, mac_no: 'B014' },
    "B_CNC015": { enable: true, display: false, model_id: 'workbache', mac_id: 39, mac_no: 'B015' },
    "B_CNC016": { enable: true, display: false, model_id: 'workbache', mac_id: 40, mac_no: 'B016' },
    "B_CNC017": { enable: true, display: false, model_id: 'workbache', mac_id: 41, mac_no: 'B017' },
    "B_CNC018": { enable: true, display: false, model_id: 'workbache', mac_id: 42, mac_no: 'B018' },
    "B_CNC019": { enable: true, display: false, model_id: 'workbache', mac_id: 43, mac_no: 'B019' },
    "B_CNC020": { enable: true, display: false, model_id: 'plc', mac_id: 44, mac_no: 'B020' },
    "B_CNC021": { enable: true, display: false, model_id: 'plc', mac_id: 45, mac_no: 'B021' },
    "B_CNC022": { enable: true, display: false, model_id: 'avg1', mac_id: 46, mac_no: 'B022' },
    "B_CNC023": { enable: true, display: false, model_id: 'cangku', mac_id: 47, mac_no: 'B023' },
    "B_CNC024": { enable: false, display: false, model_id: 'daogui4', mac_id: -5, mac_no: '' },
    
    
}
if ( typeof module != 'undefined' ) {
    module.exports = model;
}